export const siteConfig = {
  title: "Create Next App",
  description: "Generated by create next app",
  links: {
    github: "https://github.com/vishkx/nextjs16_shadcn_template",
    github_api: "https://api.github.com/repos/vishkx/nextjs16_shadcn_template"
  },
}

export const META_THEME_COLORS = {
  light: "#ffffff",
  dark: "#09090b",
}
